### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zzqiuzz** [amazingTest/Taisite-Platform#16]
HI 我启动了项目 但是网页 显示Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.  这是什么原因？

**Comment by amazingTest** [comment]
确认真的启动了吗，可以看看控制台的输出

**Comment by zzqiuzz** [comment]
D:\Bin\Bin\python37\python.exe D:/AutoTest/Taisite-Platform/backend/run.py
D:\Bin\Bin\python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Bin\Bin\python37\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
D:\Bin\Bin\python37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
D:\Bin\Bin\python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Bin\Bin\python37\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
D:\Bin\Bin\python37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)
 * Debugger is active!
 * Debugger PIN: 347-652-330
 * Running on http://127.0.0.1:5050/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Nov/2020 17:23:20] "GET /index/api/login HTTP/1.1" 404 -

**Comment by zzqiuzz** [comment]
是这个 127.0.0.1 - - [19/Nov/2020 17:24:25] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [19/Nov/2020 17:24:26] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [19/Nov/2020 17:24:29] "GET / HTTP/1.1" 404 -   浏览器访问的是  http://127.0.0.1:5050/

**Comment by amazingTest** [comment]
dist 文件夹在项目下吗

**Comment by zzqiuzz** [comment]
可以了 谢谢
