### ISSUE TITLE
本地已有mongo Container占用27017，只修改AUTOTEST_PLATFORM_MONGO_PORT 无法部署成功

### ISSUE THREAD

**Issue by apert4160** [amazingTest/Taisite-Platform#2]
我在本地已经有一个`mongo Container`跑在`27017`端口上

部署`Taisite-Platrome` 时：
 - 修改`/etc/profile`->`AUTOTEST_PLATFORM_MONGO_PORT=27016`
 - 启动docker参数`-p 27016:27016`
 - 部署`sh deploy 27016`

在执行到`createAdminUser.py`时报错
>数据库连接拒绝

其他地方有需要修改`mongo`的端口的吗？

**Comment by amazingTest** [comment]
第一个 **issue** 来了~

我来描述一下根据你的问题我的一些观点与想法~

0. docker容器化部署中数据库连接是可以（建议）通过 **docker内网IP** 连接的，所以与 **是否已经有一个mongo Container跑在27017端口上** 无关，因为每一个 container 有不同的内网 IP。

1. 可以测试一下环境变量是否设置正确，通过 **python ./backend/config.py** 命令*。

2. 然后通过 **docker inspect** 命令查询你想连接的数据库容器的 **docker内网** IP 地址

3. 检查 数据库IP 地址是否与 环境变量设置的一致

4. **不需要修改/etc/profile->AUTOTEST_PLATFORM_MONGO_PORT=27016** ， 如果你连接的是 docker 容器内部的数据库。

5. **启动docker参数-p 27016:27016** 如果是指启动数据库的话，这样是没有任何意义的，因为你将容器内的 27016 端口（暂时没有意义的端口），映射到了宿主机的 27016 上（也没什么意义）

6. sh deploy 27016 只是表示最后访问项目的地址为 XXX.xxx.xxx: 27016   与数据库无关

综上所述，可以用以下步骤进行尝试：

0. 修改/etc/profile->AUTOTEST_PLATFORM_MONGO_PORT=27017

1. 通过 docker 内网 IP 设置数据库相关的环境变量

2. 再次运行 sh deploy

期待你的回复~

**Comment by apert4160** [comment]
感谢回复，晚些时候试过来反馈

**Comment by apert4160** [comment]
原来我们可能误会了，我原意是想另外启动一个`mongo container`，单独运行`Taisite`项目。

把环境变量配置到已经在运行的`Mongo`上，可以成功部署项目了。

建议把`README`的部署部分回滚回去，搬到另一个地方不是很友好，太功利了。（虽然不太适合在这说）

**Comment by amazingTest** [comment]
成功部署了就好~

没关系，这里没有什么不适合说的，我尊重你的建议，但我也有我自己的考虑哈
