### ISSUE TITLE
导入用例失败了，如下

### ISSUE THREAD

**Issue by a512154224** [amazingTest/Taisite-Platform#22]
导入数据异常: 表格中第 2 行的 「耗时校验/s」 值无法转换为 float: could not convert string to float:

**Comment by amazingTest** [comment]
这个报错很明显了！

**Comment by a512154224** [comment]
问题是这个我不需要校验，留空也会报错

**Comment by amazingTest** [comment]
em... 我有点印象了，你目前可以写个非常大的数比如 60 （一般接口默认超时设置就是 60）

**Comment by amazingTest** [comment]
再试试导入是否成功

**Comment by a512154224** [comment]
这样是可以的。我加了数值就通过了

**Comment by amazingTest** [comment]
em... 是个可优化的点，谢谢反馈
